version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-locabiz   # <-- força o nome do container!
    ports:
      - "6379:6379"
    volumes:
      - C:/Users/User/redis-data:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    networks:
      - localbiz-network

  backend:
    build: ./localbiz-replit
    container_name: localbiz-backend
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis-locabiz:6379
      - MONGODB_URI=${MONGODB_URI}
      - GOOGLE_PLACES_API_KEY=${GOOGLE_PLACES_API_KEY}
      - CLERK_PUBLISHABLE_KEY=${CLERK_PUBLISHABLE_KEY}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - CLERK_WEBHOOK_SIGNING_SECRET=${CLERK_WEBHOOK_SIGNING_SECRET}
    depends_on:
      - redis
    networks:
      - localbiz-network

networks:
  localbiz-network: